Added the scope of the team
solid/team pull request #39
Opened 2023-07-11 21:34 UTC by jaxoncreed

This PR summarizes the findings and perscriptions of an exercise conducted by the Solid Team to solidify the scope of the Solid Team, as represented in these meeting minutes:

- https://github.com/solid/team/blob/main/meetings/2023-04-19.md
- https://github.com/solid/team/blob/main/meetings/2023-05-03.md
- https://github.com/solid/team/blob/main/meetings/2023-05-10.md
- https://github.com/solid/team/blob/main/meetings/2023-05-10.md
- https://github.com/solid/team/blob/main/meetings/2023-06-14.md

2023-07-11 22:15 UTC, jeff-zucker commented
I propose that instead of leaving these two items blocked

 - [[Blocked] Fascilitate In-Person Solid Meetups](/tasks/inPersonMeetups.md)
 - [[Blocked] Diversity Outreach](/tasks/diversityOutreach.md)

that we create an intermediate task that moves towards fulfilling parts of those two tasks in the form of creating a **Solid Community of Practice Group** aimed at people using Solid to provide real world solutions.  I volunteer to lead the task force and will begin by setting up monthly meetings and creating a github repo and gitter chatroom for shared discussions.

I have already convened a meeting similar to what I envision for this group.  It is summarized below including the reaction of participants to the idea of an ongoing Community of Practice group :

On July 10, 2023, a meeting was held between three groups working on Solid approaches to the exchange of information between governments and their citizens.  

The Flemish government, under the auspices of the EU, has a project - [Digital Flanders](https://www.vlaanderen.be/digitaal-vlaanderen) - which enables storage, verification, and privacy-protecting access to diplomas and other certifications and plans to extend the use of Solid to the delivery of social benefits.  The project has been live since May 2023.

The [Open Commons](https://opencommons.org/Main_Page) initiative in Portland, Oregon is exploring the use of Solid in addressing issues of sustainability, smart cities, and delivery of social services. In conjunction with the U.S. National Institute of Standards and the EU, Open Commons is working to form Open Source Program Offices (OSPO) in  a number of U.S. cities joining a global network exploring how data can work in municipal governments.

In conjunction with Open Commons, the [OpenPDX PASS](https://github.com/codeforpdx/PASS) project is in late stages of development of a Solid platform that supports provision of services to houseless individuals through consolidating their personal documents in Solid Pods and providing mechanisms for social service agencies to access the documents as permitted by and under the control of the individual.  The team also has plans to extend the platform to areas such as public transit, disaster preparedness, and professional license management.

The three groups explained their projects, remarked on the many similarities, and expressed a desire for further discussion.  I agreed to work towards building a space to further these discussions - monthly meetups and a github repo.  We all agreed to work to expand the audience to other members of the Solid community of practice - organizations and individuals using Solid to accomplish real world solutions.  Participants expressed that they want the discussions to focus on getting things done rather than theoretical implications.  Other goals included developing shared solutions (code that works for more than one project); sharing information on increasing adoption of Solid by municipal governments and other agencies.

I have proposed [elsewhere](https://github.com/solid/process/pull/323#issuecomment-1623993979) that this task be carried out as part of the W3C Community Group but I believe that this task should be a Team task regardless of its eventual relationship to the CG so we should get this going as a separate action from any action or lack thereof in regard to the CG.

2023-07-12 00:43 UTC, jeff-zucker commented
Phrased similarly to the other tasks : 

# Solid Community of Practice

## Responsibilities
Members of the Solid Community of Practice team are tasked with promoting networking between organizations and individuals working on Solid solutions to real world problems.    The Team should make an effort to ensure that socially beneficial organizations and underrepresented voices are part of the target audience and highlighted in the content. 

## Task Members
 -  Jeff Zucker

2023-07-12 04:24 UTC, VirginiaBalseiro commented
> Solid Community of Practice

Name is a bit confusing to me. Could we simply follow the guidelines Jackson is proposing here and have it be a task force within Solid Team? Such as "Diversity Outreach and (Networking) Events Task" or even "project"? .

2023-07-12 04:24 UTC, VirginiaBalseiro commented on README.md
> + - [[Blocked] Converting SolidProject.org to RDF](/tasks/solidProjectRdf.md)
If we're calling out tasks that are blocked, do we need to clarify what is blocking them?

2023-07-12 04:26 UTC, VirginiaBalseiro commented on tasks/codeOfConductEnforcement.md
> +Members of the Code of Conduct Enforcement Task are responsible for enforcing the [code of conduct](https://github.com/solid/process/blob/main/code-of-conduct.md)
There is the Code of Conduct Committee, which is a separate group.

2023-07-12 07:14 UTC, VirginiaBalseiro commented
> Solid Community of Practice

Name is a bit confusing to me. It gives me the impression of a group separate from Solid Team being set up, but this is still a goal and task within the Solid Team.

Could we simply follow the guidelines Jackson is proposing here and have it be a task force within Solid Team? Such as "Diversity Outreach and (Networking) Events Task" or even "project"?

Other than that sounds good to start working towards these goals. If we can unblock some of these items that's great.

2023-07-12 16:23 UTC, jeff-zucker commented
> Name is a bit confusing to me. 

I am not fixated on that particular name.  However the name that is confusing to me is "Solid Community Group", since apparently most members of the group do not see growing the Solid Community or providing networking opportunities for community members as within the scope of that group.    Currently there are regular meetings of those interested in the specs.  I propose regular meetings of the wider community, starting with this Community of Practice Group.   If it turns out that the CG is not where the community engagement work I am proposing lands, and we end up having a separate group discussion aimed at implementers, it would make sense to me for the CG to adopt a name like Solid Specifications Community Group or similar making it clear to all that they are not the place for general discussion, community building, networking or anything other than providing feedback and getting clarity on the specifications.

2023-07-14 08:33 UTC, csarven reviewed
This is part of a series of reviews. Focusing this one on membership.md

2023-07-14 08:33 UTC, csarven commented on membership.md
> +To apply to be a Solid Team Member, send an email to info@solidproject.org. Solid Team membership is reviewed and approved by the Solid Director. Solid Team Members may also be expelled by the Solid
Where in the minutes does it say to use emails for applications? To foster transparency, applications should be done as PRs instead of emails. Ditto responses to PRs. (We'll need to have a simple template later asking key questions.. why do you want to be a member, how do you want to contribute.. ) If "privacy" is such a concern, the email should go to the Director directly instead of a select few that has access to the general info@.

2023-07-14 08:33 UTC, csarven commented on membership.md
> +## Current Members
* Tag/Re-confirm that the individuals that want to be a member (determine commitment by either in or out.. no half way).
* Membership is missing Dmitri and Barath (unless they've stated otherwise on record).
* Order alphabetically.
* 50% of the current membership is from one organisation. This demands a serious review by the Director in order to ensure diversity (among other things). Setting a maximum percentage (or some other factor) for membership per organisation would be one simple way to approach this. Another would be one vote per organisation, with the exception of independents.

2023-07-14 08:33 UTC, csarven commented on membership.md
> +| Name              | Organization                                                                          | WebId                                              |
```suggestion
| Name              | Organization                                                                          | WebID                                              |
```

2023-07-14 08:33 UTC, csarven commented on membership.md
> +| Inrupt Maintenance Team | [Inrupt]([https://www.inrupt.com](https://www.inrupt.com/))                     |                                                    |
Membership should be limited to accountable individuals, so list actual names instead of 'maintenance team' along with contact method. At least one identifiable individual needs to be present as per Responsibilities.

2023-07-27 11:05 UTC, woutermont commented
>>> [@jeff-zucker:] I propose [...] creating a **Solid Community of Practice Group** aimed at organizations and individuals using Solid to provide real world solutions.
>>
>> [@VirginiaBalseiro:] Name is a bit confusing to me. It gives me the impression of a group separate from Solid Team being set up, but this is still a goal and task within the Solid Team.
>
> [@jeff-zucker:] I am not fixated on that particular name. However the name that is confusing to me is "Solid Community Group" [...] Currently there are regular meetings of those interested in the specs. **I propose regular meetings of the wider community, starting with this Community of Practice Group.** 

@jeff-zucker, I share the opinion that "Solid Community Group" is a confusing name, but it is the name it is given by the W3C. All W3C community groups are named "XYZ Community Group". Calling it any other name is equally confusing.

I also share @VirginiaBalseiro's doubt about why we'd need a separate group with a separate name, if what we're really after is **meetings** of the whole Solid Project 🤔 I would just propose to call them **Solid Project Meetings**, organized under the Solid Project by the Solid Team. 

Granted, this does not resolve all of the confusion, especially for newcomers (I wonder if we ever can). But with good descriptions on the website and certain core READMEs on the repo's, I think most people will do fine. If not, there's absolutely nothing wrong with someone ending up at the wrong meeting, and being guided towards the right one.

2023-07-27 14:17 UTC, woutermont commented
I interpreted her following statement that way:

> It gives me the impression of a group separate from Solid Team being set up, but this is still a goal and task within the Solid Team.

But I see that I misunderstood your intention (or at least the target audience thereof), so please ignore my proposal then. If indeed it is to be a meeting and/or group specifically for implementers of all kind, you could call them the Solid Implementers Meetings, and possibly follow the suggestion has been raised of establishing a W3C Business Group to further organize things around implementation? I'm just doing suggestions, based on my now hopefully correct understanding of what your purpose was/is. 🙂

2023-08-11 09:51 UTC, csarven reviewed
camelCase URIs are strange. I suggest using lowercase and separating terms with `-`.

2023-08-28 16:28 UTC, jeff-zucker commented
I prefer the name "Practitioners" to "Implementers"  but  will settle for either.  My concern is that developers know where to go to get specific kinds of help and that those wanting to join our efforts know where there are others working on similar issues.  I see a need for at least three groups aimed at this part of our community.  

### Developer Engagement Task Force
* purpose : onboard & support developers
* audience : anyone wanting to code, regardless of skill level
* focus : learning to code  using  Solid

### Practitioner Engagement Task Force
* purpose : highlight & support real-world Solid projects
* audience : organizations & individuals creating Solid solutions
* focus : solving real-world problems using Solid

### W3C Community Group & Working Group
* purpose : move specificationss along the path to becoming standards
* audience : specification writers/editors; implementers with spec questions or spec-related feedback
* focus : building and clarifying the specifications

I volunteer to lead the Practitioners group. I envision a monthly video call for the Practitioners with eventual breakout calls for different verticals.  I would also work to build a page for the website highlighting projects, a registry of projects, github repos for project demos, inter-project discussions and eventually vertical libraries that support multiple projects.

I propose Jon Wilson to lead the Developers Task Force as a home for his onboarding work.

Both the developers and practioners groups can benefit from mentoring and hackathons but with different orientations and level of specificity.  Hopefully any hackathons organized with Team participation would coordinate with one or both of the developer and practioner task forces.

2023-08-29 15:52 UTC, TallTed commented
> camelCase URIs are strange. I suggest using lowercase and separating terms with -.

I guess you mean you prefer [kebab-case](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#kebab-case) to [camelCase](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#camel-case).

I don't find [camelCase](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#camel-case) to be any stranger in itself than the convention of [PascalCase](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#pascal-case) for classes and [camelCase](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#camel-case) for properties.

Other common alternatives are [snake_case](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#snake-case) and [PascalCase](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#pascal-case).

None of these are particularly natural or easy to write or read at all times. It probably does make some sense to pick one, as much as is possible for the permissionlessly extensible Solid "project", or to define roles for each, and to note this/these in all relevant programmer/implementer guides.

2023-08-29 18:54 UTC, csarven commented
@TallTed , I skipped mentioning the context but it was about the filenames / URLs of the tasks in this PR. Vegan kebab-case and snake_case is generally common out there and recommended - easier for humans at the very least to distinguish the terms. FWIW. Pascal/camelCase is generally common for coders.

2023-08-30 07:42 UTC, csarven commented on tasks/solidCommunityCss.md
> +Currently, SolidCommunity.net is running on NSS. In order to depricate NSS, it should be upgraded to CSS. Preferably, this upgrade will have no effecto on the users of SolidCommunity.net outside of t
```suggestion
# Migrate SolidCommunity.net server from NSS to CSS

## Responsibilities
Currently, [SolidCommunity.net](https://solidcommunity.net/) is running on [NSS](https://github.com/nodeSolidServer/node-solid-server). This work changes the server from NSS to [CSS](https://github.com/CommunitySolidServer/CommunitySolidServer/). Preferably, this change will have no effect on the users of SolidCommunity.net outside of the aesthetics of the UI. Certain components, such as WAC, will be unchanged.
```

WAC bit is as stated by @timbl in Solid Team.

2023-09-01 04:10 UTC, YetAnotherJonWilson commented
Thanks for mentioning me, @jeff-zucker !

 I would love to be a part of this team in any capacity, and if I could help by leading a group for developers, even better, as that's what I hope to focus on (development and onboarding), whether officially or unofficially.

Do I need to apply to be a part of the Solid Team? I looked at the Readme on the [main page](https://github.com/solid/team/), and followed the "Join the Solid Team" link, but it wasn't clear. Please let me know, thanks!

2023-09-05 04:06 UTC, pinfold commented
> I prefer the name "Practitioners" to "Implementers" but will settle for either. My concern is that developers know where to go to get specific kinds of help and that those wanting to join our efforts know where there are others working on similar issues. I see a need for at least three groups aimed at this part of our community.
> 
> ### Developer Engagement Task Force
> * purpose : onboard & support developers
> * audience : anyone wanting to code, regardless of skill level
> * focus : learning to code  using  Solid
> 
> ### Practitioner Engagement Task Force
> * purpose : highlight & support real-world Solid projects
> * audience : organizations & individuals creating Solid solutions
> * focus : solving real-world problems using Solid
> 
> ### W3C Community Group & Working Group
> * purpose : move specificationss along the path to becoming standards
> * audience : specification writers/editors; implementers with spec questions or spec-related feedback
> * focus : building and clarifying the specifications
> 
> I volunteer to lead the Practitioners group. I envision a monthly video call for the Practitioners with eventual breakout calls for different verticals. I would also work to build a page for the website highlighting projects, a registry of projects, github repos for project demos, inter-project discussions and eventually vertical libraries that support multiple projects.
> 
> I propose Jon Wilson to lead the Developers Task Force as a home for his onboarding work.
> 
> Both the developers and practioners groups can benefit from mentoring and hackathons but with different orientations and level of specificity. Hopefully any hackathons organized with Team participation would coordinate with one or both of the developer and practioner task forces.

The Practitioner Engagement Task Force is an excellent idea. We have a team working on a platform to streamline the delivery of social and municipal services and it would be very valuable to share experiences with other teams working on real-world Solid projects.

2023-09-22 15:36 UTC, hzbarcea commented
> The Practitioner Engagement Task Force is an excellent idea. We have a team working on a platform to streamline the delivery of social and municipal services and it would be very valuable to share experiences with other teams working on real-world Solid projects.

👍  Totally agree @pinfold @jeff-zucker. I think it's actually very necessary (more than an excellent idea) from a **community** point of view. Growing the community is needed initially for developing the core of the spec. I think we reached a point where the community should be more about adoption.

2024-01-12 09:07 UTC, michielbdejong commented
In the light of https://hackmd.io/kN52sfoJQauugdSmQFp8fA I think it's better if we remove the explicit mention of Solid World from the team scope, and instead mention something like "support Solid-branded events like Solid Symposium and others as and when needed"

2024-01-12 14:31 UTC, jeff-zucker commented
The members of the Solid Team are in a unique position to know what is going on in Solid - we create and monitor changes to the website and community server; we hear about the work of the CG, COCC, Practitioners, and other key parts of Solid directly; we monitor the forums and chat rooms; we have the participation of @timbl.  There is no other group I am aware of that covers such a broad spectrum of the Solidverse or is in a better position to let the world know about Solid. Not that it should ever be *the* source, but the Team is the broadest source. Wnen Timea was MCing Solid World she always left space for a short "news from the Team" section and I think that should be reinstated.

Further, I believe we as a Team have a responsibility to model and promote the principles we believe in - the use of the web for net social benefit and diversity of all kinds.  If there is ever going to be a concerted outreach to the global south or to other under-represented populations, where should it come from if not the Solid Team? We need people to write specs and create data models.  How can we attract them without outreach? And if that outreach is not based on diversity, how else will anyone in the outside world gain confidence that Solid practices what it preaches? And any such diviersity-based outreach will be weaker if it is not done in coordination with others and is not done by a group of people with a broad knowledge of the Solidverse.

For these reasons, I am not in favor of off-loading Solid World or other initiatives.  I am in favor of Virginia's proposal to have them carried out by community members under the oversight of the Team.  I would hope that some of these initiatives can be supported by companies but with the understanding that the oversight remains with the Team.  I would also hope that we can find support from a foundation for a broader outreach and diversity effort.  If such funding is obtained it would be even more important to coordinate the outreach and the publicizing so having Team events, publications, and web resources under one roof will be even more important.

2024-01-12 14:57 UTC, michielbdejong commented
>  carried out by community members under the oversight of the Team

* I don't think this oversight is necessary (the organisers of Solid Symposium and of Solid World are not juniors who need supervision).
* I don't think it's practical (going through a committee for each change in a speaker's list is too much overhead). 
* despite team involvement that may have existed in the past, I don't think the *current* organisers of any of these events are requesting help from the team
* I don't think the team should impose its rule from a position of authority on event organisers who are not requesting our help

That's why I say, let events be organised by whoever is organising them, if any problem arises around branding or conduct then the team or the CoCC can step in, but otherwise I think we should not stand in the way of anyone and let a thousand flowers bloom.

I also think any communication around Solid World or other events *can* say they are "organised by the community" but they *cannot* say they are "organised by the Solid team" or "organised by the Solid project".

I'm documenting this here because Virginia asked me to. Whenever I say the team has no business "supervising" the Solid World organisers, I get the response "but we have it in our scope". So my solution is: let's remove it from our scope, be done with it, and spend our energy on other things such as https://matrix.to/#/!SWuPNCVLGJhfHYZIxj:gitter.im/$A9EsN5kMVhMsuo5G7RoDYyoruEPZdxCxoUvM3pxRAwY?via=gitter.im&via=matrix.org

2024-01-12 15:39 UTC, jeff-zucker commented
> * I don't think this oversight is necessary (the organisers of Solid Symposium and of Solid World are not juniors who need supervision).

You misunderstand my use of the word oversight, which was perhaps the wrong word.  I don't mean it in the sense of supervise but  in the sense of coordinate.  The Team should support a coordinated effort to broaden  the Solid community and that includes things like Solid World.  But not in isolation, we should have a showcase like it, and a  website, and a newsletter which work in coordination to broaden Solid.  

Just to give one example of a coordinated outreach.  Suppose Women in Solid came to the Team with the idea of a coordinated burst of attention to broadening gender diversity in Solid.  We could have forum discussions, newsletter items, and a Solid World made up of developers from the Women in Solid group.  That would take coordination.

> * I don't think it's practical (going through a committee for each change in a speaker's list is too much overhead).

We have been over this multiple times for the past year and have said repeatedly that no one expects that .  What we expect are things like coordination on topics, and a transparent selection process oriented towards the principles of DEI.

> * I don't think the team should impose its rule from a position of authority on event organisers who are not requesting our help

What we have expected is that the organizer of Solid World is a member of the Solid Team.  It is not a matter of the Team dictating to that organizer, but of the organizer being part of the team with the expectation that the organizer give general reports when appropriate and be open to suggestions and discussion from other team members.,  No one is interested in micro-managing.  If the current organizer of Solid World had participated in this way, even minimally, we would not be having this discussion.

> I think we should not stand in the way of anyone and let a thousand flowers bloom.

There is nothing about the Team taking responsibility for a single event that in any way prevents or discourages anyone else from blooming.  If Inrupt wants to continue with "Inrupt Solid Showcase", they are welcome to, as is anyone else to create any event they want.  Why would the fact of the Team having an event prevent anyone else from having an event?

2024-01-15 14:18 UTC, VirginiaBalseiro commented
> I propose that instead of leaving these two items blocked
> 
> * [[Blocked] Fascilitate In-Person Solid Meetups](/tasks/inPersonMeetups.md)
> * [[Blocked] Diversity Outreach](/tasks/diversityOutreach.md)

I have incorporated this here: https://github.com/solid/team/pull/39/commits/9538bb9273048bf7594280e7de289bac7c598ad5

Let me know if that covers it or I should modify anything.

2024-01-15 14:45 UTC, michielbdejong approved these changes

2024-01-15 15:29 UTC, jeff-zucker approved these changes

2024-01-18 18:59 UTC, TallTed requested changes

2024-01-18 18:59 UTC, TallTed commented on tasks/solid-world.md
> +The Team should make an effort to ensure that socially beneficial organizations and underrepresented voices are part of the target audience and highlighted in the content.
```suggestion
Members of the Solid World Organizing Team are tasked with compiling information for organizing and hosting the Solid World webinar. Presenters for the webinar may be sourced from anywhere. The organizers will provide an open and transparent process for submissions, and will document and inform the Solid Team of the submissions and the rationale for selection, as well as other planned annoucements, prior to the event.

The Team should make an effort to ensure that socially beneficial organizations and under-represented voices are part of the target audience and highlighted in the content.
```

2024-01-18 19:27 UTC, TallTed requested changes
Grammar, punctuation, typos, etc. Intended to be editorial, and not to change the meaning of anything.

2024-01-18 19:27 UTC, TallTed commented on tasks/practitioners-engagement.md
> +Members of the [Practitioners team](https://github.com/solid-contrib/practitioners) are tasked with engaging with individuals and organizations building Solid software for use in the real world. The
```suggestion
Members of the [Practitioners Task Force](https://github.com/solid-contrib/practitioners) engage with individuals and organizations building Solid software for use in the real world. The Practitioners Task Force should provide networking and collaborating opportunities such as regular online meetups and github repos; provide a pathway between working practitioners and other parts of the Solid community such as the W3C Community Group, SolidProject.org, and Solid World; and support efforts to highlight and publicize the work of practitioners. In keeping with the Solid vision, the Practitioners Task Force should pay special attention to socially beneficial initiatives and strive for diversity of participation. The Practitioners lead should keep the Solid Team informed about practitioner activity.
```

2024-01-18 19:27 UTC, TallTed commented on tasks/service-maintenance.md
> +Members of the Service Maintenance task as responsible for maintaining the various technical services that support the Solid ecosystem (Listed below).
```suggestion
Members of the Service Maintenance Task Force maintain the various technical services that support the Solid ecosystem (listed below).
```

2024-01-18 19:27 UTC, TallTed commented on tasks/diversity-outreach.md
> +Posible activities include encouraging diversity and inclusion by pairing with projects that are providing social benefit and which include marginalized people in key roles, providing the projects wi
```suggestion
Members of the Diversity Outreach task force actively reach out to diverse peoples and foster a welcoming environment inside the Solid ecosystem.

Possible activities include encouraging diversity and inclusion by pairing with projects that are providing social benefit and which include marginalized people in key roles; providing the projects with networking and mentoring assistance; providing paid internships for marginalized people to participate in these projects and or in core projects which directly benefit the Solid community; creating hackathons that work on these projects; and creating ongoing online meetings and symposia to network socially-relevant projects using Solid.
```

2024-01-18 19:27 UTC, TallTed commented on README.md
> +Team members may be added or removed from this task by a majority vote at a Solid Team meeting. There must be a lead for this task. While other members may assist in the task, it is the responsibilit
```suggestion
### Task Force Membership

Team members may be added or removed from this task force by a majority vote at a Solid Team meeting. There must be a lead for this task. While other members may assist in the task, it is the responsibility of the leader to
```

2024-01-18 19:27 UTC, TallTed commented on tasks/developer-onboarding-experience.md
> +## Task Members
```suggestion
## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/diversity-outreach.md
> +## Task Members
```suggestion
## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/fundraising.md
> +There are certain tasks that the Solid Team wants to do, but does not have the resources to do it. That's where fundraising is important. Members of the fundraising task are responsible for finding g
```suggestion
There are certain tasks that the Solid Team wants to do, but does not have the necessary resources. That's where fundraising is important. Members of the fundraising task force find grants/methods to raise funds for the Solid team.
```

2024-01-18 19:27 UTC, TallTed commented on tasks/fundraising.md
> +## Task Members
```suggestion
## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/in-person-meetups.md
> +## Task Members
```suggestion
Members of the In Person Meetups Task Force provide resources to help in-person Solid meetups around the world.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on README.md
> +### Ongoing Tasks
```suggestion
### Ongoing Task Forces
```

2024-01-18 19:27 UTC, TallTed commented on README.md
> +### One-off Tasks
```suggestion
### One-off Task Forces
```

2024-01-18 19:27 UTC, TallTed commented on tasks/diversity-outreach.md
> +This task is under the scope of the [Solid Practitioners Engagement Task Force](practitioners-engagement.md)
```suggestion
This task force is under the scope of the [Solid Practitioners Engagement Task Force](practitioners-engagement.md)
```

2024-01-18 19:27 UTC, TallTed commented on tasks/manage-social-media.md
> +Members are tasked with updating and admining the various Social Media accounts, enforcing the Code of Conduct when necessary, and posting content.
```suggestion
Members are tasked with updating and administering the various Social Media accounts, enforcing the Code of Conduct when necessary, and posting content.
```

2024-01-18 19:27 UTC, TallTed commented on tasks/meeting-organization.md
> +## Task Members
```suggestion
Members of the Meeting Organization Task Force are responsible for organizing meetings. This includes sending calendar invites, messages, and emails to update members of reoccurring and special meetings. It also includes ensuring that meeting minutes are recorded in the [meetings folder](/meetings/).

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/practitioners-engagement.md
> +## Task Members
```suggestion
Members of the [Practitioners team](https://github.com/solid-contrib/practitioners) are tasked with engaging with individuals and organizations building Solid software for use in the real world. The team should provide networking and collaborating opportunities such as regular online meetups and github repos; provide a pathway between working practitioners and other parts of the Solid community such as the W3C Community Group, SolidProject.org, and Solid World; support efforts to highlight and publicize the work of practitioners. In keeping with the Solid vision, the team should pay special attention to socially beneficial initiatives and strive for diversity of participation. The Practioner lead should keep the Team informed about practitioner activity.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/solid-community-css.md
> +## Task Members
```suggestion
Currently, [SolidCommunity.net](https://solidcommunity.net/) is running on [NSS](https://github.com/nodeSolidServer/node-solid-server). This work changes the server from NSS to [CSS](https://github.com/CommunitySolidServer/CommunitySolidServer/). We intend the aesthetics of the UI to be the only effect of this change on the users of SolidCommunity.net. Certain components, such as WAC, will be unchanged.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/solid-community-maintenance.md
> +## Task Members
```suggestion
Members of the SolidCommunity.net Maintenance Task Force maintain the servers for SolidCommunity.net.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/solid-newsletter.md
> +## Task Members
```suggestion
Mebers of the Solid Newsletter Task Force compile information for, write, and send a monthly newsletter. Information for the newsletter may be sourced from anywhere, but a publicly available submission method (like a PR or a public form) must be one source. The Task Force should keep a written record of the rationale for the inclusion or exclusion of submitted information. The Task Force should make an effort to ensure that socially beneficial organizations and underrepresented voices are part of the target audience and highlighted in the content.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/solid-project-content-pass.md
> +## Task Members
```suggestion
The Task Force performs an assessment of SolidProject.org and presents the findings to the Solid Team. With the team's approval, the updates are done.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/solid-project-rdf.md
> +## Task Members
```suggestion
SolidProject.org currently uses Jekyl and GitHub. We want to create an RDF-based site so that we're dogfooding our own technology. Perhaps the best change would be creating one, RDF-based source of truth for information like Solid Team members, and apps listed on the apps page. We would also want to establish a technical process for people to propose new information to pages and for the Solid team to review it.

Note: this change would not affect the hosting of the Solid Specification on GitHub, unless spec members want it to.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/solid-world.md
> +## Task Members
```suggestion
Members of the Solid World Organizing Team compile information for organizing and hosting the Solid World webinar. Presenters for the webinar may be sourced from anywhere. The organizers will provide an open and transparent process for submissions, and will document and inform the Solid Team of the submissions and the rationale for selection, as well as other planned announcements, prior to the event.

The Team should make an effort to ensure that socially beneficial organizations and under-represented voices are part of the target audience and highlighted in the content.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/team-administration.md
> +## Task Members
```suggestion
Members of the Team Administration Task Force ensure all other members of the team have proper access to the services they need to perform their tasks. They are also responsible for revoking access of any members that have been removed from a task. Finally, the Team Administration Task Force is responsible for ensuring all documents in the solid/team repository are updated to reflect the current state of the Solid Team.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on tasks/user-onboarding-experience.md
> +## Task Members
```suggestion
The Solid Team will create tutorials to help users onboard to Solid.

## Task Force Members
```

2024-01-18 19:27 UTC, TallTed commented on team.md
> +* How you would like to contribute
```suggestion
* Why do you want to be a member?
* How would you like to contribute?
```

2024-01-18 22:45 UTC, TallTed requested changes
Just a bit more...

2024-01-18 22:45 UTC, TallTed commented on tasks/fundraising.md
> +There are certain tasks that the Solid Team wants to do, but does not have the necessary resources. That's where fundraising is important. Members of the fundraising task force find grants/methods to
```suggestion
There are certain tasks that the Solid Team wants to do, but does not have the necessary resources. That's where fundraising is important. Members of the fundraising task force find grants and other means by which to raise funds for the Solid team.
```

2024-01-18 22:45 UTC, TallTed commented on tasks/meeting-organization.md
> +Members of the Meeting Organization Task Force are responsible for organizing meetings. This includes sending calendar invites, messages, and emails to update members of reoccurring and special meeti
```suggestion
Members of the Meeting Organization Task Force organize meetings. This includes sending calendar invites, messages, and emails to update members of reoccurring and special meetings. It also includes ensuring that meeting minutes are recorded in the [meetings folder](/meetings/).
```

2024-01-18 22:45 UTC, TallTed commented on tasks/practitioners-engagement.md
> +## Task Members
```suggestion
Members of the [Practitioners Engagement Task Force](https://github.com/solid-contrib/practitioners) engage with individuals and organizations building Solid software for use in the real world. The Practitioners Task Force should provide networking and collaborating opportunities such as regular online meetups and github repos; provide a pathway between working practitioners and other parts of the Solid community such as the W3C Community Group, SolidProject.org, and Solid World; and support efforts to highlight and publicize the work of practitioners. In keeping with the Solid vision, the Practitioners Task Force should pay special attention to socially beneficial initiatives and strive for diversity of participation. The Practitioners lead should keep the Solid Team informed about practitioner activity.

## Task Force Members
```

2024-01-19 01:49 UTC, jeff-zucker approved these changes

2024-01-19 01:52 UTC, oolivo reviewed
Given that this is not currently "Officially" how we work. Let's add this to the agenda for the next Solid Team meeting to discuss with the larger team. It would also be useful to link to a definition for consensus as it means different things to different people.

2024-01-19 01:59 UTC, merged

2024-01-19 02:01 UTC, VirginiaBalseiro commented
> Given that this is not currently "Officially" how we work. Let's add this to the agenda for the next Solid Team meeting to discuss with the larger team. It would also be useful to link to a definition for consensus as it means different things to different people.

Made a PR to discuss separately: https://github.com/solid/team/pull/49