Add missing Creators that were missed when adding team list
solid/team pull request #53
Opened 2024-01-19 17:18 UTC by VirginiaBalseiro

These names were missing due to oversight.

2024-01-19 18:24 UTC, TallTed requested changes

2024-01-19 18:24 UTC, TallTed commented on team.md
> +| Ted Thibodeau | | http://id.myopenlink.net/dataspace/person/tthibodeau#this |
```suggestion
| Ted Thibodeau     | [OpenLink Software](https://www.openlinksw.com/) | http://id.myopenlink.net/dataspace/person/tthibodeau#this |
```

2024-01-19 18:24 UTC, TallTed commented on team.md
>  | Hadrian Zbarcea   | [Inrupt]([https://www.inrupt.com](https://www.inrupt.com/))                           |                                                    |
There are several rows I cannot suggest changes to, that need this same change
```suggestion
| Hadrian Zbarcea   | [Inrupt](https://www.inrupt.com/)                           |                                                    |
```

2024-01-19 18:45 UTC, TallTed commented on team.md
>  | Nicolas Seydoux   | [Inrupt]([https://www.inrupt.com](https://www.inrupt.com/))                           |                                                    |
```suggestion
| Nicolas Seydoux   | [Inrupt](https://www.inrupt.com/)                           |                                                    |
```

2024-01-19 18:48 UTC, VirginiaBalseiro commented on team.md
>  | Nicolas Seydoux   | [Inrupt]([https://www.inrupt.com](https://www.inrupt.com/))                           |                                                    |
I just tidied up the table a bit, which messes up the diff, but I think I covered all these issues.

2024-01-19 18:52 UTC, TallTed commented on team.md
> +| Ted Thibodeau     | [OpenLink Software](https://www.openlinksw.com/) | http:/id.myopenlink.net/dataspace/person/tthibodeau#this |
```suggestion
| Ted Thibodeau     | [OpenLink Software](https://www.openlinksw.com/) | http://id.myopenlink.net/dataspace/person/tthibodeau#this |
```

2024-01-19 19:08 UTC, TallTed approved these changes
Does still cry out for a number of WebIDs, but they needn't be added in this PR.

2024-01-20 16:37 UTC, csarven approved these changes

2024-01-20 16:39 UTC, csarven commented on team.md
> +| Giselle Wenban | | https://id.inrupt.com/gisellewenban |
```suggestion
| Giselle Wenban | Inrupt | https://id.inrupt.com/gisellewenban |
```

2024-01-20 16:49 UTC, merged